version: 2.1

orbs:
  node: circleci/node@5

jobs:
  run-ui-tests:
    docker:
      - image: cimg/node:18.16-browsers
    steps:
      - checkout

      - run:
          name: Install UI dependencies
          command: |
            cd ui_tests
            npm install

      - run:
          name: Install Chrome & ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget curl gnupg
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            cd ui_tests
            npm install chromedriver --save-dev

      - run:
          name: Start ChromeDriver
          command: |
            npx chromedriver --port=9515 --url-base=wd/hub &
            sleep 5

      - run:
          name: Run UI tests
          command: |
            cd ui_tests
            npm run test || true # Allow tests to fail without failing the job
          environment:
            CONTINUE_ON_FAIL: true

      - store_artifacts:
          path: ui_tests/tests_output/nightwatch-html-report
          destination: nightwatch-report

  run-api-tests:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout

      - run:
          name: Install API dependencies
          command: |
            cd api_tests
            npm install

      - run:
          name: Start Mock Server & Wait
          command: |
            cd api_tests
            npm run dev 
          background: true

      - run:
          name: Wait for Server
          command: sleep 5

      - run:
          name: Run API Tests
          command: |
            cd api_tests
            npm run test || true # Allow tests to fail without failing the job
          environment:
            CONTINUE_ON_FAIL: true

      - store_artifacts:
          path: api_tests/reports
          destination: api-test-report

workflows:
  version: 2
  full-test-workflow:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
