version: 1

orbs:
  node: circleci/node@5

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout

      - run:
          name: Install npm dependencies
          command: npm install

      - run:
          name: Install Chrome & ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget curl gnupg
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            npm install chromedriver --save-dev

      - run:
          name: Start ChromeDriver
          command: |
            npx chromedriver --port=9515 --url-base=wd/hub &
            sleep 5

      - run:
          name: Run UI tests
          command: |
            cd ui_tests
            npm install
            npm run test || true
          environment:
            CONTINUE_ON_FAIL: true

      - store_artifacts:
          path: ui_tests/tests_output/nightwatch-html-report
          destination: nightwatch-report

      - run:
          name: Download wait-for-it.sh
          command: |
            curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
            chmod +x wait-for-it.sh

      - run:
          name: Start API server
          command: |
            cd api_tests
            npm install
            nohup npm run dev > server.log 2>&1 &
            ../wait-for-it.sh 127.0.0.1:3000 --timeout=30 --strict -- echo "Server is up!"

      - run:
          name: Run API tests
          command: |
            cd api_tests
            npm run test || true
          environment:
            CONTINUE_ON_FAIL: true

workflows:
  version: 1
  build-and-test-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
