version: 2.1

jobs:
  install_chrome:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-key.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            npm install -g chromedriver

workflows:
  version: 2
  install_chrome_workflow:
    jobs:
      - install_chrome